services:
  stremio:
    build: .
    container_name: stremio_server
    restart: unless-stopped
    environment:
      - NO_CORS=1
      - LIBVA_DRIVER_NAME=i965
      - LIBVA_DRIVER_DEVICE=/dev/dri/renderD128  # Use i965 for your Intel Haswell GPU (renderD129)
      - DISPLAY=
      - PUID=1000
      - PGID=1000
    ports:
      - "8080:8080"      # Web UI port (if applicable)
      - "11470:11470"    # Main Stremio server port
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128  # Map only your Intel iGPU render node (D129 is my nvdia GPU)
      - /dev/dri/card1:/dev/dri/card1
    volumes:
      - ~/stremio:/root/.stremio-server
